### ISSUE TITLE
How to create every 2 days task start from start date

### ISSUE THREAD

**Issue by sandy414k** [jcoutch/NCrontab-Advanced#10]
Hello,  I am using NCrontab.Advanced component for generating task instances on my Asp.Net MVC application.

Issue : I need to create a daily task which generate instances every 2 day and it should start from start date. 

Expression : 0 43 11 1/2 * ? *
Start Date : 2/22/2017 15:23
End Date   : 2/28/2017 15:23

Result (Instances Generated): 
2/23/2017 15:23
2/25/2017 15:23
2/27/2017 15:23

Expected Result :
2/22/2017 15:23
2/24/2017 15:23
2/26/2017 15:23
2/28/2017 15:23

Please explain me , why it is happening like this or give me any solution for this.

Thanks,
Sandy

**Comment by jcoutch** [comment]
Your day of month filter is 1/2, which alternates days from the first of the month (i.e. 1, 3, 5, 7, 9, etc.)  So the results are correct (well, the days are correct...the times are not...guessing that's a typo.)

Here's a working .NET Fiddle with the provided cron expression adjusted to use */2, which generates the output you're looking for (seconds and years are removed due to .NET Fiddle time/memory constraints):
[https://dotnetfiddle.net/BXRIaC](https://dotnetfiddle.net/BXRIaC)

*/2 will alternate on even days, so you'll sometimes have a 3-day gap at the end of months with 31 days, and on leap years at the end of February.  This isn't a bug with NCrontab.Advanced, but a limitation of cron expressions in general.  The answer to this StackExchange question has a good explanation of this limitation:
http://unix.stackexchange.com/questions/16093/how-can-i-tell-cron-to-run-a-command-every-other-day-odd-even
