### ISSUE TITLE
Any plan to support .net core?

### ISSUE THREAD

**Issue by rposener** [jcoutch/NCrontab-Advanced#4]
Is there any work being done to port for .net core?

**Comment by jcoutch** [comment]
I haven't had the chance to port it over yet.  This project was primarily to add new features for use in Hangfire, which is running the full framework.  I just saw your pull request (thanks btw!)  I'll check it out tonight and if everything looks good, I'll get a nuget package published.

**Comment by rposener** [comment]
thanks - looking forward to seeing it published.  Exciting news that .net core 1.0 was released today - if you need/want any changes on the PR for any 1.0 changes let me know, will be glad to help.

**Comment by rposener** [comment]
Any update on this?  Anything I can do to help?

**Comment by jcoutch** [comment]
I haven't had a chance to pull down the pull request to check out.  I'm hoping to do that this week (barring no disruptions from work/personal life.)

**Comment by rposener** [comment]
anything we can do to help with this?

**Comment by jcoutch** [comment]
I've fallen waaaay behind on maintaining my open-source projects...sorry about that!

I had a chance to look at the merge request, and the main thing I'm concerned about is that the code is essentially duplicated into it's own folder.  I'd much rather have a separate project within the existing solution that builds against .NET Core, and then just links to the existing source code files.  If you've never linked a file before, when you go to add an existing file to a project, the "Open" button in the file selection window has it's own drop-down that allows you to link the file instead of copy it.  Not very intuitive. :-)
[Adding or linking existing files to a project in Visual Studio .NET](https://support.microsoft.com/en-us/kb/306234)

If you want to get a head start on those changes, that'd help out greatly!  And my schedule has opened back up, so I'll be able to get to this a lot faster than I have in the past.

**Comment by rposener** [comment]
This is just a file copy and changing links.  Simple enough.  Just wondering why not keep a single source code, and convert to .xproj, where you can deliver a nugget that supports .net 4.x framework, and .net core?  There are 0 code changes, so why not keep it DRY?  Let me know how you want this to go, and I can get the changes made, would like to get this source out of my solution, and down to a nuget package.

**Comment by rposener** [comment]
I updated my pull request to use .net core (compiling to both .net 451 and .net core).  Hopefully that will help.  I did a quick build in VS Code, and it all compiled fine.  I removed the core path completely in the latest commit.  Can we get this updated on nuget soon?  running a "dotnet restore", then a "dotnet build" and finally a "dotnet pack" will get you from source to a valid nuget  package that supports both frameworks.

**Comment by jcoutch** [comment]
Sorry for not getting back sooner.  I have sat aside a chunk of time for my open-source projects tonight/Saturday, and will get the NuGet package out there.

**Comment by jcoutch** [comment]
I merged your changes, along with some slight changes to the project.json to only require .NETStandard in the .NETStandard build (so the package can still be used with older framework versions w/o Core dependencies.)  Version 1.2 has been pushed out to Nuget.  Let me know if you find any issues with the new package.

And thanks for your help on this!
